### ISSUE TITLE
Illegal paths may cause NullPointerException to be thrown rather than a 404 to be returned

### ISSUE THREAD

**Issue by ratskinmahoney** [alfasoftware/soapstone#10]
If a path is invoked which does not correspond to a mapped path then the following is thrown:
```
java.lang.NullPointerException
	at org.alfasoftware.soapstone.SoapstoneService.execute(SoapstoneService.java:227)
	at org.alfasoftware.soapstone.SoapstoneService.get(SoapstoneService.java:99)
```

The culprit is:
```java
Object object = webServiceClasses.get(pathKey).invokeOperation(operationName, nonHeaderParameters, headerParameters);
```
`...get(pathKey)` should be null checked.

**Comment by ratskinmahoney** [comment]
Fix has been committed
